//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketProc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gorevler()
        {
            this.Elemanlar = new HashSet<Elemanlar>();
        }
    
        public int GorevNo { get; set; }
        public string GorevAdi { get; set; }
        public string GorevTanimi { get; set; }
        public Nullable<decimal> GorevFiyat { get; set; }
        public Nullable<int> GorevSuresi { get; set; }
        public string GorevDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Elemanlar> Elemanlar { get; set; }
    }
}
