//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketProc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SirketEntities : DbContext
    {
        public SirketEntities()
            : base("name=SirketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Elemanlar> Elemanlar { get; set; }
        public virtual DbSet<Gorevler> Gorevler { get; set; }
    
        public virtual ObjectResult<ElemanArama_Result> ElemanArama(string aramaKelime)
        {
            var aramaKelimeParameter = aramaKelime != null ?
                new ObjectParameter("AramaKelime", aramaKelime) :
                new ObjectParameter("AramaKelime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ElemanArama_Result>("ElemanArama", aramaKelimeParameter);
        }
    
        public virtual int ElemanEkle(string elemanAdi, string elemanPozisyon, Nullable<decimal> elemanMaas, string elemanStatu, Nullable<int> gorevNo)
        {
            var elemanAdiParameter = elemanAdi != null ?
                new ObjectParameter("ElemanAdi", elemanAdi) :
                new ObjectParameter("ElemanAdi", typeof(string));
    
            var elemanPozisyonParameter = elemanPozisyon != null ?
                new ObjectParameter("ElemanPozisyon", elemanPozisyon) :
                new ObjectParameter("ElemanPozisyon", typeof(string));
    
            var elemanMaasParameter = elemanMaas.HasValue ?
                new ObjectParameter("ElemanMaas", elemanMaas) :
                new ObjectParameter("ElemanMaas", typeof(decimal));
    
            var elemanStatuParameter = elemanStatu != null ?
                new ObjectParameter("ElemanStatu", elemanStatu) :
                new ObjectParameter("ElemanStatu", typeof(string));
    
            var gorevNoParameter = gorevNo.HasValue ?
                new ObjectParameter("GorevNo", gorevNo) :
                new ObjectParameter("GorevNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ElemanEkle", elemanAdiParameter, elemanPozisyonParameter, elemanMaasParameter, elemanStatuParameter, gorevNoParameter);
        }
    
        public virtual ObjectResult<ElemanListele_Result> ElemanListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ElemanListele_Result>("ElemanListele");
        }
    
        public virtual int ElemanSil(Nullable<int> elemanNo)
        {
            var elemanNoParameter = elemanNo.HasValue ?
                new ObjectParameter("ElemanNo", elemanNo) :
                new ObjectParameter("ElemanNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ElemanSil", elemanNoParameter);
        }
    
        public virtual int ElemanYenile(Nullable<int> elemanNo, string elemanAdi, string elemanPozisyon, Nullable<decimal> elemanMaas, string elemanStatu, Nullable<int> gorevNo)
        {
            var elemanNoParameter = elemanNo.HasValue ?
                new ObjectParameter("ElemanNo", elemanNo) :
                new ObjectParameter("ElemanNo", typeof(int));
    
            var elemanAdiParameter = elemanAdi != null ?
                new ObjectParameter("ElemanAdi", elemanAdi) :
                new ObjectParameter("ElemanAdi", typeof(string));
    
            var elemanPozisyonParameter = elemanPozisyon != null ?
                new ObjectParameter("ElemanPozisyon", elemanPozisyon) :
                new ObjectParameter("ElemanPozisyon", typeof(string));
    
            var elemanMaasParameter = elemanMaas.HasValue ?
                new ObjectParameter("ElemanMaas", elemanMaas) :
                new ObjectParameter("ElemanMaas", typeof(decimal));
    
            var elemanStatuParameter = elemanStatu != null ?
                new ObjectParameter("ElemanStatu", elemanStatu) :
                new ObjectParameter("ElemanStatu", typeof(string));
    
            var gorevNoParameter = gorevNo.HasValue ?
                new ObjectParameter("GorevNo", gorevNo) :
                new ObjectParameter("GorevNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ElemanYenile", elemanNoParameter, elemanAdiParameter, elemanPozisyonParameter, elemanMaasParameter, elemanStatuParameter, gorevNoParameter);
        }
    
        public virtual ObjectResult<GorevArama_Result> GorevArama(string aramaKelime)
        {
            var aramaKelimeParameter = aramaKelime != null ?
                new ObjectParameter("AramaKelime", aramaKelime) :
                new ObjectParameter("AramaKelime", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GorevArama_Result>("GorevArama", aramaKelimeParameter);
        }
    
        public virtual int GorevEkle(string gorevAdi, string gorevTanimi, Nullable<decimal> gorevFiyat, Nullable<int> gorevSuresi, string gorevDurumu)
        {
            var gorevAdiParameter = gorevAdi != null ?
                new ObjectParameter("GorevAdi", gorevAdi) :
                new ObjectParameter("GorevAdi", typeof(string));
    
            var gorevTanimiParameter = gorevTanimi != null ?
                new ObjectParameter("GorevTanimi", gorevTanimi) :
                new ObjectParameter("GorevTanimi", typeof(string));
    
            var gorevFiyatParameter = gorevFiyat.HasValue ?
                new ObjectParameter("GorevFiyat", gorevFiyat) :
                new ObjectParameter("GorevFiyat", typeof(decimal));
    
            var gorevSuresiParameter = gorevSuresi.HasValue ?
                new ObjectParameter("GorevSuresi", gorevSuresi) :
                new ObjectParameter("GorevSuresi", typeof(int));
    
            var gorevDurumuParameter = gorevDurumu != null ?
                new ObjectParameter("GorevDurumu", gorevDurumu) :
                new ObjectParameter("GorevDurumu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GorevEkle", gorevAdiParameter, gorevTanimiParameter, gorevFiyatParameter, gorevSuresiParameter, gorevDurumuParameter);
        }
    
        public virtual ObjectResult<GorevElemanBirleştirme_Result> GorevElemanBirleştirme()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GorevElemanBirleştirme_Result>("GorevElemanBirleştirme");
        }
    
        public virtual ObjectResult<GorevListele_Result> GorevListele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GorevListele_Result>("GorevListele");
        }
    
        public virtual int GorevSil(Nullable<int> gorevNo)
        {
            var gorevNoParameter = gorevNo.HasValue ?
                new ObjectParameter("GorevNo", gorevNo) :
                new ObjectParameter("GorevNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GorevSil", gorevNoParameter);
        }
    
        public virtual int GorevYenile(Nullable<int> gorevNo, string gorevAdi, string gorevTanim, Nullable<decimal> gorevFiyat, Nullable<int> gorevSuresi, string gorevDurumu)
        {
            var gorevNoParameter = gorevNo.HasValue ?
                new ObjectParameter("GorevNo", gorevNo) :
                new ObjectParameter("GorevNo", typeof(int));
    
            var gorevAdiParameter = gorevAdi != null ?
                new ObjectParameter("GorevAdi", gorevAdi) :
                new ObjectParameter("GorevAdi", typeof(string));
    
            var gorevTanimParameter = gorevTanim != null ?
                new ObjectParameter("GorevTanim", gorevTanim) :
                new ObjectParameter("GorevTanim", typeof(string));
    
            var gorevFiyatParameter = gorevFiyat.HasValue ?
                new ObjectParameter("GorevFiyat", gorevFiyat) :
                new ObjectParameter("GorevFiyat", typeof(decimal));
    
            var gorevSuresiParameter = gorevSuresi.HasValue ?
                new ObjectParameter("GorevSuresi", gorevSuresi) :
                new ObjectParameter("GorevSuresi", typeof(int));
    
            var gorevDurumuParameter = gorevDurumu != null ?
                new ObjectParameter("GorevDurumu", gorevDurumu) :
                new ObjectParameter("GorevDurumu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GorevYenile", gorevNoParameter, gorevAdiParameter, gorevTanimParameter, gorevFiyatParameter, gorevSuresiParameter, gorevDurumuParameter);
        }
    }
}
